version: '2'
services:
  agent:
    image: grafana/agent:latest
    volumes:
      - ./agent/config:/etc/agent-config
      - ./logs:/var/log
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -prometheus.wal-directory=/tmp/agent/wal
    ports:
      - '12345:12345'
