server:
  log_level: debug
  http_listen_port: 12345

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: system
          pipeline_stages:
            - json:
                expressions:
                  timestamp: ts
            - timestamp:
                source: timestamp
                format: Unix
          static_configs:
            - targets:
                - localhost
              labels:
                job: greenskeeper
                __path__: /var/log/greenskeeper.log

      clients:
        - url: http://logs-prod-us-central1.grafana.net/loki/api/v1/push
          basic_auth:
            username: ${LOKI_USERNAME}
            password: ${LOKI_PASSWORD}
